name: Checkbox Options Example
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Select Options
        id: options
        run: echo "::set-output name=selected_options::${{ join(github.event.inputs.options, ',') }}"
    
         inputs:
           options:
           description: 'Select options'
           required: true
           default: 'Option 1,Option 2,Option 3'
