name: Checkbox Options Example
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Select Options
        id: options
        run: echo "::set-output name=selected_options::${{ join(github.event.inputs.options, ',') }}"

      - name: Display Selected Options
        run: echo "Selected options:${{ steps.options.outputs.selected_options }}"
