name: Checkbox Events Workflow

on:
  workflow_dispatch:
    inputs:
      checkboxes:
        description: 'Select checkboxes'
        required: true
        type: checkbox

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script based on checkboxes
        run: |
          echo "Selected checkboxes: ${{ toJson(github.event.inputs.checkboxes) }}"
          # Perform actions based on the selected checkboxes
