name: DEH mainworkflow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment 
      choice:
        type: choice
        description: Make a choice
        options:
        - drop2.yml
        - drop3.yml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Perform some action
        run: |
          if ${{ github.event.inputs.checkbox_input }} == 'true'
          then
            # Checkbox input is checked
            echo "Checkbox is checked!"
          else
            # Checkbox input is not checked
            echo "Checkbox is not checked!"
          fi

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}" 
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
