name: main workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - drop2.yml
          - drop3.yml
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

      strategy:
      matrix:
      choice: [drop2.yml, drop3.yml]  # Available choices

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run based on choice
        run: |
          if [ "${{ matrix.choice }}" == "drop2.yml" ]; then
            echo "Running drop2 workflow"
            # Execute drop2 workflow steps
          elif [ "${{ matrix.choice }}" == "drop3.yml" ]; then
            echo "Running drop3 workflow"
            # Execute drop3 workflow steps
          else
            echo "Invalid choice"
            exit 1
          fi
