name: Your Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
     inputs:
      choice:
         type: choice
         description: Make a choice
         options:
         - DB
         - BAT
         - WAR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          # Build and test commands here
          inputs:
          enable-option:
          description: 'Enable the option'
          default: false
          required: false
          type: boolean
            
      - name: Perform additional action
        if: ${{ github.workflow.inputs.enable-option == 'true' }}
        run: |
          # Additional action if the checkbox is enabled

