name: Multi-Workflow Selection
on:
  push:
    branches:
      - main

jobs:
  workflow_selection:
    runs-on: ubuntu-latest
    steps:
      - name: Select Workflows
        id: workflow_input
        run: echo "::set-output name=selected_workflows::${{ join(github.event.inputs.workflows, ',') }}"
    
    inputs:
      workflows:
        description: 'Select workflows'
        required: true
        default: 'workflow1,workflow2,workflow3'
        # Add additional workflow options if needed
