name: DEH Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment 
      choice:
        type: choice
        description: Make a choice
        options:
        - Database
        - batch
        - bat
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}" 
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
