name: Dropdown List Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
     inputs:
      choice:
         type: choice
         description: Make a choice
         options:
         - drop2
         - drop3
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check choice parameter and run corresponding workflow
        if: steps.choice.outputs.choice_parameter == 'drop2'
        run: |
          echo "Running drop2 workflow"

      - name: Check choice parameter and run corresponding workflow
        if: steps.choice.outputs.choice_parameter == 'drop3'
        run: |
          echo "Running drop3 workflow"
      - name: Checkout repository
        uses: actions/checkout@v2
      # Add additional steps for your workflow
