name: Dropdown List Workflow
on:
  push:
    branches:
      - main
       choice:
        type: choice
        description: Make a choice
        options:
        - drop2
        - drop3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Dropdown Value
        id: dropdown
        run: |
          echo "::set-output name=options::drop2,drop3"
      - name: Checkout repository
        uses: actions/checkout@v2
      # Add additional steps for your workflow
