name: Choice Parameters Workflow
on:
  workflow_dispatch:
    inputs:
      option:
        description: 'Select an option'
        required: true
        default: 'Option 1'
        options:
          - 'Option 1'
          - 'Option 2'
          - 'Option 3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Selected Options
        run: echo "Selected options:${{ github.event.inputs.options }}"
      # Add additional steps for your workflow
