name: Dropdown List Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Prompt for choice parameter
        id: choice
      - name: Check choice parameter and run corresponding workflow
        if: steps.choice.outputs.choice_parameter == 'drop2'
        run: |
          echo "Running drop2 workflow"

      - name: Check choice parameter and run corresponding workflow
        if: steps.choice.outputs.choice_parameter == 'drop3'
        run: |
          echo "Running drop3 workflow"
